const path = require("path");
global.__basedir = path.parse(__filename).dir;

const argsparser = require("./Console/argsparser.js");
const process = require("process");

function DrawAutoKubeHeader() {
  var header =
    "DQrilpHilojilojilojilojilojilZfilpHilojilojilZfilpHilpHilpHilojilojilZfilojilojilojilojilojilojilojilojilZfilpHilojilojilojilojilojilZfilpHilojilojilZfilpHilpHilojilojilZfilojilojilZfilpHilpHilpHilojilojilZfilojilojilojilojilojilojilZfilpHilojilojilojilojilojilojilojilZcNCuKWiOKWiOKVlOKVkOKVkOKWiOKWiOKVl+KWiOKWiOKVkeKWkeKWkeKWkeKWiOKWiOKVkeKVmuKVkOKVkOKWiOKWiOKVlOKVkOKVkOKVneKWiOKWiOKVlOKVkOKVkOKWiOKWiOKVl+KWiOKWiOKVkeKWkeKWiOKWiOKVlOKVneKWiOKWiOKVkeKWkeKWkeKWkeKWiOKWiOKVkeKWiOKWiOKVlOKVkOKVkOKWiOKWiOKVl+KWiOKWiOKVlOKVkOKVkOKVkOKVkOKVnQ0K4paI4paI4paI4paI4paI4paI4paI4pWR4paI4paI4pWR4paR4paR4paR4paI4paI4pWR4paR4paR4paR4paI4paI4pWR4paR4paR4paR4paI4paI4pWR4paR4paR4paI4paI4pWR4paI4paI4paI4paI4paI4pWQ4pWd4paR4paI4paI4pWR4paR4paR4paR4paI4paI4pWR4paI4paI4paI4paI4paI4paI4pWm4pWd4paI4paI4paI4paI4paI4pWX4paR4paRDQrilojilojilZTilZDilZDilojilojilZHilojilojilZHilpHilpHilpHilojilojilZHilpHilpHilpHilojilojilZHilpHilpHilpHilojilojilZHilpHilpHilojilojilZHilojilojilZTilZDilojilojilZfilpHilojilojilZHilpHilpHilpHilojilojilZHilojilojilZTilZDilZDilojilojilZfilojilojilZTilZDilZDilZ3ilpHilpENCuKWiOKWiOKVkeKWkeKWkeKWiOKWiOKVkeKVmuKWiOKWiOKWiOKWiOKWiOKWiOKVlOKVneKWkeKWkeKWkeKWiOKWiOKVkeKWkeKWkeKWkeKVmuKWiOKWiOKWiOKWiOKWiOKVlOKVneKWiOKWiOKVkeKWkeKVmuKWiOKWiOKVl+KVmuKWiOKWiOKWiOKWiOKWiOKWiOKVlOKVneKWiOKWiOKWiOKWiOKWiOKWiOKVpuKVneKWiOKWiOKWiOKWiOKWiOKWiOKWiOKVlw0K4pWa4pWQ4pWd4paR4paR4pWa4pWQ4pWd4paR4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWd4paR4paR4paR4paR4pWa4pWQ4pWd4paR4paR4paR4paR4pWa4pWQ4pWQ4pWQ4pWQ4pWd4paR4pWa4pWQ4pWd4paR4paR4pWa4pWQ4pWd4paR4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWd4paR4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWd4paR4pWa4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWd";
  console.log(Buffer.from(header, "base64").toString("utf-8"));
}

const actions = {
  build: require('./Commands/InstallApplicationCommand').command,
  init: require('./Commands/InitProjectConfigurationCommand').command,
  //publish: require('./Commands/PublishApplicationCommand').command,

  //'install-deps': require('./Commands/InstallDependenciesCommand').command,
};

DrawAutoKubeHeader();
argsparser.functionExecutor(process.argv, actions);
